Fix header-substitution error message.
We should use $<, to get the name of the header, rather than $^, which also
contains the name of the directory stamp file.

diff --git a/libdtrace/Build b/libdtrace/Build
--- a/libdtrace/Build
+++ b/libdtrace/Build
@@ -125,14 +125,14 @@ $(m4-dlib-targets): $(objdir)/dlibs/%.d: $$(foreach name,$$(notdir %.d.in), \
 		$(libdtrace-build_DIR)def-end.m4 $< > $@; \
         if [[ $$? -ne 0 ]]; then \
 		cat $@.h.err >&2; \
-		echo "Error: Not all tokens in $^ defined in headers." >&2; \
+		echo "Error: Not all tokens in $< defined in headers." >&2; \
 		rm -f $@.h $@.h.err; \
 		exit 1; \
 	fi
 	if ! grep -q __def_replace $@.h; then \
 		cat @$.h; \
                 cat $@.h.err >&2; \
-		echo "Error: Preprocessing of header included in $^ failed." >&2; \
+		echo "Error: Preprocessing of header included in $< failed." >&2; \
 		rm -f $@.h $@.h.err; \
 		exit 1; \
 	fi
