Revamp .d.in script processing path again.
Before now, we have been translating the output of the C preprocessor into a sed
script with M4, then passing the .d.in scripts through sed to replace tokens
with their expanded values.  This works, but has problems, principally that if
a token is specified on only some machines we cannot elide the relevant D.

So, instead, do all the processing via M4.  M4 now reads in the following
files to produce the output .d script:

  - def-replace.m4 (replacement for sed-replace.m4).

    Define __def_replace(), calls to which are generated by the C preprocessor
    as before. However, rather than expanding to a sed expression, this expands
    to an M4 macro expansion that replaces the literal C macro with its
    value. (We cannot use @wrapped@ names any more, because these are not valid
    M4 macro names -- at least, not unless changeword() is used, and
    changeword() is both deprecated and optional, so we cannot rely on it). We
    also emit a better error if expansion fails, naming the macro for which
    expansion failed.

    This also arranges to use /* C style comments */, and starts throwing away
    all output.  Output is not resumed until d-subst.m4 (see below).

  - The output of the C preprocessor run over a D-script-specific M4 file
    (e.g. io.m4).

    This is what used to be io.sed.in: cpp is used to replace names of macros
    with calls to __def_replace() giving the macro name and its value.
    __def_replace then generates approriate M4 macros.

  - d-subst.m4.

    This changes the quoting character to a sequence not valid in D ([[ ]] for
    now), defines a pair of macros which can be used to define optional D inline
    variables (which should expand to nothing if the platform does not define
    the macro), and cancels the diversion, causing future output to be sent to
    the D script.

  - The d.in script itself.

    This can include calls to def_constant() and def_constant_renamed() to
    define optional constants.  Pay attention to quoting: the C macro name
    must be [[quoted]]!  (References to the macro which should be replaced
    with its value no longer need to be surrounded with @at@ signs.)

This has uglinesses, notably that optional parts of the D script are now written
in something that looks quite unlike D: but at least eliding optional parts of
the D script is now *possible*.

diff --git a/libdtrace/Build b/libdtrace/Build
--- a/libdtrace/Build
+++ b/libdtrace/Build
@@ -67,7 +67,7 @@ $(libdtrace-build_DIR)dt_lex.c: $(libdtrace-build_DIR)dt_grammar.h $(libdtrace-b
 	$(call describe-target,LEX,$(libdtrace-build_DIR)dt_lex.c)
 	flex -o$(libdtrace-build_DIR)dt_lex.c $(libdtrace-build_DIR)dt_lex.l
 
-SED_DLIBS += \
+M4_DLIBS += \
 	procfs.d \
 	io.d \
 	ip.d \
@@ -77,7 +77,7 @@ SED_DLIBS += \
 	udp.d
 
 BUILD_DLIBS += \
-	$(SED_DLIBS) \
+	$(M4_DLIBS) \
 	errno.d \
 	signal.d
 
@@ -89,34 +89,27 @@ WORKING_DLIBS = errno.d \
                 signal.d \
                 unistd.d
 
-# Normal substitutions.
-
-$(objdir)/%.sed: $(libdtrace-build_DIR)%.sed.in
-	$(call describe-target,SED,$<)
-	if [[ ! -d $(KERNELDIR)/include/linux ]]; then \
-		echo "Error: Point KERNELDIR=... at the Linux kernel source." >&2; \
+# M4-driven substitutions.
+$(foreach dlib,$(filter $(WORKING_DLIBS),$(M4_DLIBS)),$(call src-name,libdtrace,$(dlib))): \
+		%.d: %.d.in
+	$(call describe-target,M4,$*.d.in)
+	$(PREPROCESS) -x c -Ilibdtrace/$(ARCHINC) -I$(KERNELDIR)/include -I$(KERNELDIR)/arch/$(KERNELARCH)/include \
+		      -D_KERNEL -D__KERNEL__ $(addsuffix .m4,$*) 2>$@.h.err | tee $@.h | \
+	m4 --prefix-builtins $(libdtrace-build_DIR)def-replace.m4 - $(libdtrace-build_DIR)/d-subst.m4 $*.d.in > $@; \
+        if [[ $$? -ne 0 ]]; then \
+		cat $@.h.err >&2; \
+		echo "Error: Not all tokens in $^ defined in headers." >&2; \
+		rm -f $@.h $@.h.err; \
 		exit 1; \
 	fi
-	$(PREPROCESS) -x c -I$(KERNELDIR)/include -I$(KERNELDIR)/arch/$(KERNELARCH)/include \
-		      -D_KERNEL -D__KERNEL__ $< 2>$@.h.err | tee $@.h | \
-	    m4 $(libdtrace-build_DIR)sed-replace.m4 - > $@
-	if ! grep -q __sed_replace $@.h; then \
-		cat $@.h.err >&2; \
+	if ! grep -q __def_replace $@.h; then \
+		cat @$.h; \
+                cat $@.h.err >&2; \
 		echo "Error: Preprocessing of header included in $^ failed." >&2; \
 		rm -f $@.h $@.h.err; \
 		exit 1; \
 	fi
-	rm -f $@.h $@.h.err; \
-	if grep -q @@@@SUBST-FAIL@@@@ $@; then \
-		cat $@; \
-		echo "Error: Not all tokens in $^ defined in headers." >&2; \
-		exit 1; \
-	fi
-
-$(foreach dlib,$(filter $(WORKING_DLIBS),$(SED_DLIBS)),$(call src-name,libdtrace,$(dlib))): \
-		%.d: $$(addprefix $$(objdir)/,$$(notdir %.sed)) %.d.in
-	$(call describe-target,SED,$*.d.in)
-	sed -f $(addprefix $(objdir)/,$(notdir $*.sed)) < $*.d.in > $@
+	rm -f $@.h $@.h.err;
 
 PHONIES += dlibs working-dlibs
 TARGETS += dlibs working-dlibs
